# Tag 1. Kapitel 3. Data Frame
## Lektion 20.2 Data Frame Operationen. Ein- und Ausgabe
### Import/Export von Daten aus/in verschiedenen Quellen.

Data Frames sind die Arbeitstiere von R, deshalb erstellen wir uns in dieser Lektion eine Art "Cheatsheet" der üblichsten Ein- und Ausgabe-Operationen. Dadurch wird diese Lektion extrem nützlich sein und uns im weiteren Verlauf des Kurses extrem viel Zeit sparen, da wir Data Frames bereits kennen und auf unser Cheatsheet zurückgreifen können. 

Wir werden uns eine Übersicht der folgenden typischen Operationen verschaffen:

* Daten in/von Zwischenablage (Clipboard) schreiben/lesen
* Daten in/von CSV-Datei schreiben/lesen
* Daten in/von Excel-Datei schreiben/lesen
* Daten in/von eine(r) Datenbank schreiben/lesen

**Tipp: Informationen Anbindung von R an verschiedene Datenbanken kann man auf der Webseite [Databases using R](https://db.rstudio.com/databases/) erfahren**

# Import und Export von Daten

## Manuelle Datenkorrektur in R Studio

In [4]:
leer <- data.frame() # Leerer Data Frame
c1 <- 1:15 # Vektor von Zahlen
c2 <- letters[1:15] # Verktor von Zeichen
df <- data.frame(spalte.name.1=c1,spalte.name.2=c2)

# Erstellte Datensätze anpassen und ausgeben 
df <- edit(df) # läuft nur in R Studio (in R Studio ausprobieren)
df

ERROR: Error in edit(df): 'edit()' not yet supported in the Jupyter R kernel

## Daten aus der Zwischenablage (Clipboard) lesen

In [7]:
# Daten aus der Zwischenablage (Clipboard) lesen
clp.dat <- read.table(file="clipboard",sep="\t", header=TRUE) # Tabulator (\t) als Trenner nutzen
clp.dat

# Daten manuell anpassen
clp.dat = edit(clp.dat) #läuft nur in R Studio

   Date       Open    High     Low      Close   Adj.Close
1  2018-12-12 1068.00 1081.650 1062.790 1063.68 1063.68
2  2018-12-13 1068.07 1079.760 1053.930 1061.90 1061.90
3  2018-12-14 1049.98 1062.600 1040.790 1042.10 1042.10
4  2018-12-17 1037.51 1053.150 1007.900 1016.53 1016.53
5  2018-12-18 1026.09 1049.480 1021.440 1028.71 1028.71
6  2018-12-19 1033.99 1062.000 1008.050 1023.01 1023.01
7  2018-12-20 1018.13 1034.220  996.360 1009.41 1009.41
8  2018-12-21 1015.30 1024.020  973.690  979.54  979.54
9  2018-12-24  973.90 1003.540  970.110  976.22  976.22
10 2018-12-26  989.01 1040.000  983.000 1039.46 1039.46
11 2018-12-27 1017.15 1043.890  997.000 1043.88 1043.88
12 2018-12-28 1049.62 1055.560 1033.100 1037.08 1037.08
13 2018-12-31 1050.96 1052.700 1023.590 1035.61 1035.61
14 2019-01-02 1016.57 1052.320 1015.710 1045.85 1045.85
15 2019-01-03 1041.00 1056.980 1014.070 1016.06 1016.06
16 2019-01-04 1032.59 1070.840 1027.418 1070.71 1070.71
17 2019-01-07 1071.50 1074.000 1054.760 1068.39 1068.39
18 2019-01-08 1076.11 1084.560 1060.530 1076.28 1076.28
19 2019-01-09 1081.65 1082.630 1066.400 1074.66 1074.66
20 2019-01-10 1067.66 1071.150 1057.710 1070.33 1070.33
21 2019-01-11 1063.18 1063.775 1048.480 1057.19 1057.19
22 2019-01-14 1046.92 1051.530 1041.255 1044.69 1044.69
23 2019-01-15 1050.17 1080.050 1047.340 1077.15 1077.15
24 2019-01-16 1080.00 1092.375 1079.340 1080.97 1080.97
25 2019-01-17 1079.47 1091.800 1073.500 1089.90 1089.90
26 2019-01-18 1100.00 1108.352 1090.900 1098.26 1098.26
27 2019-01-22 1088.00 1091.510 1063.470 1070.52 1070.52
28 2019-01-23 1077.35 1084.930 1059.750 1075.57 1075.57
29 2019-01-24 1076.48 1079.475 1060.700 1073.90 1073.90
30 2019-01-25 1085.00 1094.000 1081.820 1090.99 1090.99
31 2019-01-28 1080.11 1083.000 1063.800 1070.08 1070.08
32 2019-01-29 1072.68 1075.150 1055.865 1060.62 1060.62
33 2019-01-30 1068.43 1091.000 1066.850 1089.06 1089.06
34 2019-01-31 1103.00 1117.330 1095.410 1116.37 1116.37

ERROR: Error in edit(clp.dat): 'edit()' not yet supported in the Jupyter R kernel

## Daten in Zwischenablage (Clipboard) speichern

In [8]:
# clp.dat Data Frame in Clipboard speichern 
write.table(x=clp.dat,file = "clipboard",sep = "\t")

In [9]:
# Prüfen, ob die Speicherung funktioniert hat
read.table(file="clipboard",sep="\t", header=TRUE)

   Date       Open    High     Low      Close   Adj.Close
1  2018-12-12 1068.00 1081.650 1062.790 1063.68 1063.68
2  2018-12-13 1068.07 1079.760 1053.930 1061.90 1061.90
3  2018-12-14 1049.98 1062.600 1040.790 1042.10 1042.10
4  2018-12-17 1037.51 1053.150 1007.900 1016.53 1016.53
5  2018-12-18 1026.09 1049.480 1021.440 1028.71 1028.71
6  2018-12-19 1033.99 1062.000 1008.050 1023.01 1023.01
7  2018-12-20 1018.13 1034.220  996.360 1009.41 1009.41
8  2018-12-21 1015.30 1024.020  973.690  979.54  979.54
9  2018-12-24  973.90 1003.540  970.110  976.22  976.22
10 2018-12-26  989.01 1040.000  983.000 1039.46 1039.46
11 2018-12-27 1017.15 1043.890  997.000 1043.88 1043.88
12 2018-12-28 1049.62 1055.560 1033.100 1037.08 1037.08
13 2018-12-31 1050.96 1052.700 1023.590 1035.61 1035.61
14 2019-01-02 1016.57 1052.320 1015.710 1045.85 1045.85
15 2019-01-03 1041.00 1056.980 1014.070 1016.06 1016.06
16 2019-01-04 1032.59 1070.840 1027.418 1070.71 1070.71
17 2019-01-07 1071.50 1074.000 1054.760 1068.39 1068.39
18 2019-01-08 1076.11 1084.560 1060.530 1076.28 1076.28
19 2019-01-09 1081.65 1082.630 1066.400 1074.66 1074.66
20 2019-01-10 1067.66 1071.150 1057.710 1070.33 1070.33
21 2019-01-11 1063.18 1063.775 1048.480 1057.19 1057.19
22 2019-01-14 1046.92 1051.530 1041.255 1044.69 1044.69
23 2019-01-15 1050.17 1080.050 1047.340 1077.15 1077.15
24 2019-01-16 1080.00 1092.375 1079.340 1080.97 1080.97
25 2019-01-17 1079.47 1091.800 1073.500 1089.90 1089.90
26 2019-01-18 1100.00 1108.352 1090.900 1098.26 1098.26
27 2019-01-22 1088.00 1091.510 1063.470 1070.52 1070.52
28 2019-01-23 1077.35 1084.930 1059.750 1075.57 1075.57
29 2019-01-24 1076.48 1079.475 1060.700 1073.90 1073.90
30 2019-01-25 1085.00 1094.000 1081.820 1090.99 1090.99
31 2019-01-28 1080.11 1083.000 1063.800 1070.08 1070.08
32 2019-01-29 1072.68 1075.150 1055.865 1060.62 1060.62
33 2019-01-30 1068.43 1091.000 1066.850 1089.06 1089.06
34 2019-01-31 1103.00 1117.330 1095.410 1116.37 1116.37

## Daten von CSV-Datei lesen

In [10]:
# Aus CSV-Datei lesen (aktuelles Verzeichnis)
goog <- read.csv('GOOG_EN.csv')
head(goog) # erste Datensätze zeigen

  Date       Open    High    Low     Close   Adj.Close Volume
1 2018-12-12 1068.00 1081.65 1062.79 1063.68 1063.68   1523800
2 2018-12-13 1068.07 1079.76 1053.93 1061.90 1061.90   1329800
3 2018-12-14 1049.98 1062.60 1040.79 1042.10 1042.10   1686600
4 2018-12-17 1037.51 1053.15 1007.90 1016.53 1016.53   2385400
5 2018-12-18 1026.09 1049.48 1021.44 1028.71 1028.71   2192500
6 2018-12-19 1033.99 1062.00 1008.05 1023.01 1023.01   2479300

## Daten in CSV-Datei schreiben

In [11]:
# Ausgabe zu CSV
write.csv(df, file='demo.csv', row.names = FALSE) 

# Aus "frischgechriebener" CSV-Datei lesen und Daten anzeigen
rd <- read.csv('demo.csv')
head(rd)

  spalte.name.1 spalte.name.2
1 1             a
2 2             b
3 3             c
4 4             d
5 5             e
6 6             f

## Daten von Excel-Datei lesen

In [10]:
# Ggf. Excel-Pakete laden (wenn nichts bereits passiert)
install.packages("readxl")
library(readxl)

package 'readxl' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\dm_78\AppData\Local\Temp\RtmpWaECRr\downloaded_packages

In [13]:
# Rufe Info der Arbeitsblätter durch read.excel auf
tsla <- read_excel('TSLA.xlsx',sheet='TSLA_EN')

# geladene Datensätze zeigen (erste 6) 
head(tsla)
summary(tsla)

  Date       Open       High       Low        Close      Adj Close  Volume
1 2018-12-12 369.420013 371.910004 365.160004 366.600006 366.600006 5027000
2 2018-12-13 370.149994 377.440002 366.750000 376.790009 376.790009 7365900
3 2018-12-14 375.000000 377.869995 364.329987 365.709991 365.709991 6337600
4 2018-12-17 362.000000 365.700012 343.880005 348.420013 348.420013 7674000
5 2018-12-18 350.540009 351.549988 333.690002 337.029999 337.029999 7100000
6 2018-12-19 337.600006 347.010010 329.739990 332.970001 332.970001 8274200

     Date               Open               High               Low
 Length:252         Length:252         Length:252         Length:252
 Class :character   Class :character   Class :character   Class :character
 Mode  :character   Mode  :character   Mode  :character   Mode  :character
    Close            Adj Close            Volume
 Length:252         Length:252         Length:252
 Class :character   Class :character   Class :character
 Mode  :character   Mode  :character   Mode  :character

## Daten in Excel-Datei schreiben

In [7]:
# Ggf. Excel-Pakete laden (wenn nichts bereits passiert)
install.packages("xlsx")
library(xlsx)

Warning message:
"package 'xlsx' is in use and will not be installed"

In [8]:
# Daten in eine Excell-Datei speichern
f <- "demo_1.xlsx"
s <- "Data_1" 
# Standard-Methode 
write.xlsx(df, f, sheetName = s, col.names = TRUE, row.names = FALSE, append = FALSE)

In [11]:
# Aus "frischgechriebener" Excel-Datei lesen und Daten anzeigen
d <- read_excel(f, s)
head(d)

  spalte.name.1 spalte.name.2
1 1             a
2 2             b
3 3             c
4 4             d
5 5             e
6 6             f

In [12]:
f2 <- "demo_2.xlsx"
s2 <- "Data_2" 
# Optimierte Methode(schneller bei großen Dateien)
write.xlsx2(goog, f2, sheetName = s2, col.names = TRUE, row.names = FALSE, append = FALSE)

ERROR: Error in is.data.frame(x): Objekt 'goog' nicht gefunden

In [18]:
# Aus "frischgechriebener" Excel-Datei lesen und Daten anzeigen
g <- read_excel(f2, s2)
head(g)

  Date       Open    High    Low     Close   Adj.Close Volume
1 2018-12-12 1068.00 1081.65 1062.79 1063.68 1063.68   1523800
2 2018-12-13 1068.07 1079.76 1053.93 1061.90 1061.90   1329800
3 2018-12-14 1049.98 1062.60 1040.79 1042.10 1042.10   1686600
4 2018-12-17 1037.51 1053.15 1007.90 1016.53 1016.53   2385400
5 2018-12-18 1026.09 1049.48 1021.44 1028.71 1028.71   2192500
6 2018-12-19 1033.99 1062.00 1008.05 1023.01 1023.01   2479300

## Daten aus/in Datenbank lesen/schreiben

In [35]:
# Ggf ODBC-Pakete installieren (wenn nicht vorhanden)
install.packages("DBI")
install.packages("odbc")

Warning message:
"package 'DBI' is in use and will not be installed"Warning message:
"package 'odbc' is in use and will not be installed"

In [36]:
# Datenbank Bibliotheken laden
library(DBI)
library(odbc)

In [37]:
# Verbindung öffnen 
# Achtung! Ggf. Verbindungsparameter anpassen.
con <- dbConnect(odbc::odbc(), 
                 Driver = "SQL Server", 
                 Server = "localhost\\SQLEXPRESS", 
                 Database = "R_STAT", 
                 Trusted_Connection = "True")

In [38]:
# init
cars.table <- "cars"

In [39]:
# cars-Tabelle anlegen bzw. überschreiben (mtcars ist ein in R eingebauter Data Frame)
dbWriteTable(con, cars.table, mtcars, overwrite=TRUE)

In [40]:
#prüfen, ob tabelle existiert
dbExistsTable(con, cars.table)

[1] TRUE

In [41]:
# in Schema vorhandene Tabellen auflisten
head(dbListTables(con))

[1] "cars"                "trace_xe_action_map" "trace_xe_event_map"
[4] "CHECK_CONSTRAINTS"   "COLUMN_DOMAIN_USAGE" "COLUMN_PRIVILEGES"

In [42]:
# cars-Tabelle auslesen
cars <- dbReadTable(con, cars.table)
# cars Data Frame ausgeben
cars

   row_names           mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
1  Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
2  Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
3  Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
4  Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
5  Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
6  Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
7  Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
8  Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
9  Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
10 Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
11 Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
12 Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
13 Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
14 Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
15 Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
16 Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
17 Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
18 Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
19 Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
20 Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1
21 Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
22 Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
23 AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
24 Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
25 Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
26 Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
27 Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
28 Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
29 Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
30 Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
31 Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
32 Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [43]:
# Neue Sätze anhängen
dbWriteTable(con, cars.table, cars, append=TRUE)

In [44]:
# Prüfen, ob neue Daten angekommen sind
cars2 <- dbReadTable(con, cars.table)
cars2

    row_names           mpg  cyl disp  hp  drat wt    qsec  vs  am  gear carb
1   Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0   1   4    4
2   Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0   1   4    4
3   Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1   1   4    1
4   Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1   0   3    1
5   Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0   0   3    2
6   Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1   0   3    1
7   Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0   0   3    4
8   Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1   0   4    2
9   Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1   0   4    2
10  Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1   0   4    4
11  Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1   0   4    4
12  Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0   0   3    3
13  Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0   0   3    3
14  Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0   0   3    3
15  Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0   0   3    4
16  Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0   0   3    4
17  Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0   0   3    4
18  Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1   1   4    1
19  Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1   1   4    2
20  Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1   1   4    1
21  Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1   0   3    1
22  Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0   0   3    2
23  AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0   0   3    2
24  Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0   0   3    4
25  Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0   0   3    2
26  Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1   1   4    1
27  Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0   1   5    2
28  Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1   1   5    2
29  Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0   1   5    4
30  Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0   1   5    6
... ...                 ...  ... ...   ... ...  ...   ...   ... ... ...  ...
35  Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1   1   4    1
36  Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1   0   3    1
37  Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0   0   3    2
38  Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1   0   3    1
39  Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0   0   3    4
40  Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1   0   4    2
41  Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1   0   4    2
42  Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1   0   4    4
43  Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1   0   4    4
44  Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0   0   3    3
45  Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0   0   3    3
46  Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0   0   3    3
47  Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0   0   3    4
48  Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0   0   3    4
49  Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0   0   3    4
50  Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1   1   4    1
51  Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1   1   4    2
52  Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1   1   4    1
53  Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1   0   3    1
54  Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0   0   3    2
55  AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0   0   3    2
56  Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0   0   3    4
57  Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0   0   3    2
58  Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1   1   4    1
59  Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0   1   5    2
60  Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1   1   5    2
61  Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0   1   5    4
62  Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0   1   5    6
63  Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0   1   5    8
64  Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1   1   4    2

In [45]:
# cars-Tabelle löschen
dbRemoveTable(con, name = cars.table)

In [46]:
#prüfen, ob cars-Tabelle gelöscht worden ist
dbExistsTable(con, cars.table)

[1] FALSE

In [47]:
# Datenbank-Verbindung schliessen (immer ausführen um Datenbank-Verbindungsressourcen freizugeben)
dbDisconnect(con)

Herzlichen Glückwunsch! Sie sind mit dem 2. Teil der Lektion N° 20 fertig!

#### Bitte denkt daran, dieses Notebook als Referenz für spätere Lektionen und Aufgaben zu verwenden.